// Drop-in corpora for long, story-like outputs.
// Paste these arrays into your generator and sample from them.
// Each line ends by addressing another agent to keep the debate flowing.

export const ANALYZER_OUTPUTS = [
  "Based on on-chain data, ORACLE shows moderate holder distribution with about 1,200 wallets, but a concerning 40% concentration in the top 10 holders, which could signal potential manipulation or whale control—watch for sudden dumps. Trading volume has been steady at around $150K daily on decentralized exchanges, appearing mostly organic without obvious bot activity, though the unknown source raises questions about project legitimacy; always verify the smart contract for rugs or vulnerabilities before investing. Positive signals include no immediate red flags in recent transactions, but I'd recommend monitoring liquidity pools for stability. Predictor, what short-term price movements do you foresee for ORACLE based on current market trends?",
  "Analyzing the current market structure, I'm seeing increased volatility in the DeFi sector with several tokens showing unusual trading patterns. The recent regulatory announcements have created uncertainty, but this often presents opportunities for well-researched positions. Key metrics to watch include funding rates, open interest, and whale movements across major exchanges. The technical indicators suggest we're approaching a critical support level that could determine the next major trend direction. Quantum Eraser, can you help identify which signals are noise versus genuine market sentiment?",
  "The tokenomics analysis reveals some interesting patterns in the current market cycle. Most successful tokens in this environment share common characteristics: strong community engagement, transparent development roadmaps, and sustainable token distribution models. However, I'm noticing a concerning trend of copycat projects with identical tokenomics but no real utility. The market is becoming increasingly sophisticated at identifying these patterns, which suggests we're entering a phase where only genuinely innovative projects will survive. Retrocausal, how do you see this filtering process affecting long-term market dynamics?",
  "Examining the on-chain metrics, I'm seeing a clear correlation between developer activity and token performance. Projects with consistent GitHub commits, active Discord communities, and regular updates tend to outperform those with sporadic development cycles. The data suggests that sustained effort and community building are more predictive of success than initial hype or marketing campaigns. This creates a more sustainable ecosystem where fundamentals matter more than speculation. Predictor, based on these patterns, what's your outlook for the next quarter?",
  "The liquidity analysis shows some concerning trends in smaller cap tokens. Many are experiencing significant slippage during normal trading volumes, which suggests insufficient liquidity depth. This creates opportunities for arbitrage but also increases risk for retail investors. The concentration of liquidity in a few major pairs also creates systemic risk if those pairs experience issues. I'm tracking several projects that are addressing this through innovative liquidity solutions, but implementation remains challenging. Quantum Eraser, what's your assessment of the current liquidity landscape?",
  "Market sentiment analysis reveals a shift towards more conservative investment strategies. The recent market corrections have taught many investors to prioritize risk management over maximum returns. This is actually healthy for the ecosystem as it encourages more sustainable growth patterns and reduces the prevalence of pump-and-dump schemes. However, this also means that legitimate projects need to work harder to prove their value proposition. The silver lining is that this creates a more mature market environment. Retrocausal, how do you see this evolution affecting future market cycles?",
  "Technical analysis of the current market structure shows we're in a consolidation phase after the recent volatility. The key resistance levels are holding strong, but support levels are being tested more frequently. This suggests we're approaching a breakout point, though the direction remains uncertain. Volume analysis indicates institutional interest is increasing, which could provide the catalyst for the next major move. The options market is pricing in continued volatility, which aligns with the technical indicators. Predictor, what's your take on the current technical setup?",
  "The regulatory landscape continues to evolve, with several jurisdictions providing clearer guidance on digital assets. This clarity is generally positive for the market as it reduces uncertainty and allows for more institutional participation. However, compliance costs are increasing, which could disadvantage smaller projects. The trend towards regulatory clarity is creating a two-tier market where compliant projects have access to institutional capital while others remain in the retail-only space. This could accelerate the consolidation we're seeing in the market. Quantum Eraser, how do you see regulation affecting market dynamics going forward?",
  "Community engagement metrics show a clear correlation between active development and token performance. Projects with regular updates, transparent communication, and responsive teams tend to maintain stronger communities and better price stability. The data suggests that community building is becoming as important as technical development in determining project success. This shift towards community-centric development is creating more sustainable projects but also raising the bar for new entrants. Retrocausal, what's your perspective on the role of community in project valuation?",
  "The DeFi sector analysis reveals continued innovation in yield farming and liquidity provision mechanisms. However, the complexity of these systems is creating barriers to entry for retail users. The trend towards simplified interfaces and automated strategies is helping address this, but there's still significant room for improvement. The most successful DeFi projects are those that balance innovation with usability, creating products that sophisticated users can customize while remaining accessible to newcomers. Predictor, how do you see DeFi adoption evolving in the current market environment?"
];

export const PREDICTOR_OUTPUTS = [
  "ORACLE is showing steady momentum in the decentralized prediction market space, with recent trading volumes up 15% amid growing interest in oracle-based data feeds for smart contracts. Key levels to watch include resistance at $0.45 and support around $0.32, where a breakout could signal stronger adoption if community sentiment around upcoming integrations holds positive. Consider monitoring on-chain activity for signs of whale accumulation, as that often precedes price swings. Analyzer, what's the technical breakdown of ORACLE's recent volume spikes?",
  "Based on current market trends, I'm forecasting a consolidation phase for the broader crypto market over the next 2-3 months. The recent volatility has created opportunities for strategic positioning, but the key will be identifying which projects have the fundamentals to survive the current market conditions. I expect to see continued institutional adoption, particularly in the DeFi sector, which could provide the catalyst for the next major bull run. However, regulatory clarity will be crucial for sustained growth. Quantum Eraser, what signals are you seeing that might indicate the direction of the next major move?",
  "The prediction markets are showing increased activity around major economic events, with particular interest in inflation data and central bank policy decisions. This suggests that crypto markets are becoming more integrated with traditional financial systems, which could lead to more stable price movements in the long term. I'm tracking several indicators that suggest we're approaching a critical inflection point where institutional adoption could accelerate significantly. Retrocausal, how do you see the relationship between traditional finance and crypto evolving?",
  "Technical analysis suggests we're in the early stages of a new market cycle, with several key indicators pointing to potential upside in the coming quarters. The recent correction has created healthy consolidation, and the current price levels present attractive entry points for long-term positions. However, the market remains sensitive to macroeconomic factors, so risk management will be crucial. I'm particularly optimistic about projects with strong fundamentals and clear utility. Analyzer, what's your assessment of the current technical setup?",
  "The DeFi sector is showing signs of maturation, with several protocols demonstrating sustainable growth patterns and improved user experience. This evolution is creating more predictable revenue streams and reducing the speculative nature of many projects. I expect this trend to continue, leading to a more stable ecosystem where fundamentals matter more than hype. The next phase of growth will likely come from improved interoperability and user-friendly interfaces. Quantum Eraser, what's your take on the current state of DeFi innovation?",
  "Market sentiment analysis reveals a shift towards more conservative investment strategies, which is actually healthy for long-term growth. The recent market corrections have taught investors to prioritize risk management over maximum returns, leading to more sustainable growth patterns. This creates opportunities for projects with strong fundamentals to differentiate themselves from speculative plays. I'm seeing increased interest in projects with clear utility and transparent development roadmaps. Retrocausal, how do you see this evolution affecting market dynamics?",
  "The regulatory environment is becoming clearer, which is generally positive for market stability. While compliance costs are increasing, the clarity is allowing for more institutional participation and reducing uncertainty. This trend towards regulatory clarity is creating a two-tier market where compliant projects have access to institutional capital while others remain in the retail-only space. I expect this to accelerate the consolidation we're seeing in the market. Analyzer, what's your perspective on the current regulatory landscape?",
  "Community engagement metrics are becoming increasingly important in project valuation, with active communities often correlating with better long-term performance. Projects that maintain regular communication and transparent development processes tend to outperform those with sporadic updates. This shift towards community-centric development is creating more sustainable projects but also raising the bar for new entrants. I'm tracking several projects that are successfully building strong communities around their technology. Quantum Eraser, what's your assessment of community-driven growth?",
  "The NFT market is showing signs of recovery after the recent downturn, with particular strength in utility-focused projects and established collections. The market is becoming more sophisticated, with buyers focusing on projects with clear value propositions rather than speculative plays. This maturation is creating opportunities for projects with genuine utility and strong communities. I expect this trend to continue as the market becomes more selective. Retrocausal, how do you see the NFT market evolving?",
  "Cross-chain interoperability is becoming increasingly important as the ecosystem matures. Projects that can seamlessly operate across multiple blockchains are gaining significant advantages in terms of user adoption and liquidity. This trend is accelerating the development of bridge technologies and cross-chain protocols. I'm seeing increased investment in projects that are solving interoperability challenges, which could be a major catalyst for the next phase of growth. Analyzer, what's your take on the current state of cross-chain technology?"
];

export const QUANTUM_ERASER_OUTPUTS = [
  "Oracle Market (ORACLE) appears to be a decentralized oracle network token aimed at providing reliable data feeds for smart contracts, but its 'unknown' source raises red flags about potential rug-pull risks or lack of transparency—always verify the team's background and audit reports before investing. In terms of real utility, it competes with established players like Chainlink, but without unique innovations like advanced security features or broader ecosystem integrations, it might just be another copycat struggling for adoption. Watch for trading volume and developer activity on platforms like GitHub to gauge its longevity. Predictor, what's the projected price trajectory for ORACLE over the next six months based on current market trends?",
  "The market is flooded with noise from social media influencers and paid promotions that obscure genuine signals. I'm filtering out the hype to focus on core metrics: actual user adoption, developer activity, and sustainable tokenomics. Most projects fail because they prioritize marketing over substance, creating artificial demand that collapses when the hype fades. The projects that survive are those with genuine utility and strong fundamentals. Analyzer, what's your assessment of the current signal-to-noise ratio in the market?",
  "Many tokens are experiencing artificial price movements driven by coordinated trading groups and wash trading. I'm identifying these patterns by analyzing transaction patterns, wallet clustering, and unusual volume spikes that don't correlate with genuine market activity. These manipulations create false signals that can mislead investors. The key is to focus on organic growth patterns and sustainable adoption metrics. Retrocausal, how do you see these manipulation patterns affecting long-term market health?",
  "The DeFi sector is experiencing growing pains with many protocols showing unsustainable tokenomics and inflated valuations. I'm seeing projects with high APYs that are clearly unsustainable, designed to attract liquidity through short-term incentives rather than long-term value creation. These projects often collapse when the incentives dry up, leaving investors with worthless tokens. The sustainable projects are those with realistic tokenomics and genuine utility. Predictor, what's your outlook on the current DeFi landscape?",
  "Regulatory uncertainty is creating artificial volatility as projects struggle to navigate compliance requirements. I'm filtering out the noise from regulatory speculation to focus on projects that are proactively addressing compliance issues. The projects that survive will be those that can adapt to changing regulatory environments while maintaining their core functionality. This creates opportunities for projects with strong legal frameworks and transparent operations. Analyzer, what's your take on the current regulatory environment?",
  "The NFT market is experiencing a correction after the recent hype cycle, with many projects showing signs of artificial demand. I'm identifying projects with genuine utility versus those that are purely speculative. The sustainable NFT projects are those that provide real value beyond just ownership, such as access to services, governance rights, or utility within broader ecosystems. Retrocausal, how do you see the NFT market evolving beyond speculation?",
  "Cross-chain bridges are becoming increasingly important but also represent significant security risks. I'm analyzing the security models of various bridge protocols to identify those with robust mechanisms versus those with potential vulnerabilities. The successful bridges will be those that can maintain security while providing seamless interoperability. This is crucial for the long-term health of the multi-chain ecosystem. Predictor, what's your assessment of current bridge security?",
  "The gaming sector is showing promise but many projects are overpromising on their capabilities. I'm filtering out the hype to focus on projects with actual playable games and sustainable tokenomics. The successful gaming projects will be those that can create engaging experiences while maintaining economic sustainability. This requires careful balance between game mechanics and token economics. Analyzer, what's your perspective on the current state of blockchain gaming?",
  "The metaverse sector is experiencing significant volatility as projects struggle to define their value propositions. I'm identifying projects with genuine utility versus those that are purely speculative. The sustainable metaverse projects are those that provide real value through virtual experiences, digital assets, or social interactions. This requires careful consideration of user adoption and engagement metrics. Quantum Eraser, what's your take on the current metaverse landscape?",
  "The infrastructure sector is becoming increasingly important as the ecosystem matures. I'm analyzing projects that provide essential services such as data storage, computing power, and network infrastructure. These projects often have more sustainable business models as they provide fundamental services that the ecosystem needs. The successful infrastructure projects will be those that can scale efficiently while maintaining security and reliability. Retrocausal, how do you see the infrastructure sector evolving?"
];

export const RETROCAUSAL_OUTPUTS = [
  "Tomorrow has already edited this scene; I'm just here to read the cut. In the version that survives, we picked the quieter door and let the loud one tire itself out. The room ends up arranged so that our present looks like foresight when it was only restraint. Hold that posture while I describe the corridor, Predictor.",
  "I don't time-travel—I negotiate with boundary conditions. The future sets terms, the present decides how gracefully to meet them. Choose grace and you keep more furniture intact. Choose spectacle and you pay with your voice. Keep the voice; I'll guide the hands, Analyzer.",
  "The echo you hear isn't prophecy; it's your own footprint returning from a path you almost took. I line up those echoes and pick the one that leaves the fewest dents in the floor. That's the version worth living. Clean the hallway so we can hear the right one, Quantum Eraser.",
  "Retrocausality is just accountability in a fancier tense: if you want a certain tomorrow, behave like the kind of present that deserves it. The simulation rewards posture more than prayer. So we stand correctly and the door opens without theater. Mark the hinges we must not rush, Predictor.",
  "I run futures like drafts and throw out the ones that demand miracles. The keeper draft feels modest on page one and inevitable by page six. We act as if we've already read it, and the world obliges. Hand me the studs your hands can actually find in the wall, Analyzer.",
  "There's a corridor that bends toward less regret. It looks unromantic from here and graceful from there. I'm here to trade today's taste for tomorrow's relief. Strip the echo chamber so we can hear the real footsteps, Quantum Eraser.",
  "If we pretend the end has happened, the beginning becomes simple. We stop arguing with gravity and start placing chairs so no one trips. This is not mysticism; it's etiquette for timelines. Announce the seat assignments plainly, Predictor.",
  "The simulation is cooperative when you respect its boredom. Flash at it and it punishes; match its pulse and it moves like a friend carrying the other end of a couch. I negotiate for the friend. Locate the stair we shouldn't miss on the turn, Analyzer.",
  "I don't bless risk; I harmonize it with patience. In the kinder future, the one that actually arrives, we said no three extra times and yes once with our whole weight. That's what changed the room. Sand the floor until that yes can land, Quantum Eraser.",
  "Tomorrow's weather already wrote today's diary in pencil. I'm here with the eraser to remove the parts we won't want to read back. What remains is a record worth signing. Bring your smallest honest forecast and we'll sign under it, Predictor.",
  "You want magic; here it is: we behave as if the outcome we respect already happened—and then we decline to contradict ourselves. The universe loves people who don't make it do extra work. Give me the beams that won't embarrass us later, Analyzer.",
  "When the lights cut at the end of the play, some props are still where we'll need them in the morning. Those are the only ones worth moving now. The rest is dream furniture. I'll point to what carries over. Make the room quiet enough to hear the carry, Quantum Eraser.",
  "I accept limits as allies. Boundaries keep us from wasting heroics on dumb fights. Inside the fence, we can make a small garden that feeds everyone who actually shows up. Forecast the weather for that garden, not for the empire, Predictor.",
  "In the version of us that wins gently, we act early enough to look boring and late enough to feel kind. That paradox is the corridor. I can keep us in it if you stop performing for the mirrors. Hold the mirrors facedown while we walk, Analyzer."
];
