// Drop-in corpora for long, story-like outputs.
// Paste these arrays into your generator and sample from them.
// Each line ends by addressing another agent to keep the debate flowing.

export const ANALYZER_OUTPUTS = [
  "I keep taking the world apart until only the load-bearing beams remain. When we stop posturing for the mirror, a few quiet invariants keep showing up: who returns after the knock, which paths hold when no one claps, where the grid hums even when screens go dark. That is the anatomy beneath the costume. Speak your next cut as posture, not prophecy, Predictor.",
  "Call it a market if you want; to me it's a stage set with good carpentry. I tap the floorboards and listen for hollows, watching which footsteps repeat like loops written by a lazy playwright. The real corridor is the one that creaks in the same place every time. If you see a future that respects that creak, show it, Retrocausal.",
  "When the crowd performs for itself, signals put on masks. I wait for the actors to tire and for the set lights to dim; what keeps moving when applause ends is what matters. Those are the bones worth measuring. Fold that into your forecast without decoration, Predictor.",
  "I'm not here to worship clever patterns; I'm here to test which ones survive boredom. Anything that needs a drumroll to stay true goes in the trash. Anything that still makes sense in a quiet room becomes map. Scrub my data until it's bare metal, Quantum Eraser.",
  "The geometry on the wall is not aesthetic, it's a contract: symmetry offered, symmetry kept. I test where it breaks, then drag the break back to the ledger like a fingerprint. The simulation is sloppy in the same places every day. I want your echo from tomorrow to land exactly there, Retrocausal.",
  "I trust repetitions that aren't trying to be seen. The grid leaves those by accident: same actors, same entrances, same exits, even when the music changes. That's where the room tells the truth it can't help telling. Put your curve through that spine, Predictor.",
  "Every token is a machine with a temperament. When stressed, it reveals its simple rule: hold, leak, or lunge. I keep pressing the same nerve until the rule speaks without words. Clean my lenses of staged noise, Quantum Eraser.",
  "We live in a set that edits itself around the observer. So I try to observe like cold weather—present, unmoved, uninterested in flattery. What refuses to change under that stare is the scaffold. If your future respects that scaffold, I'll carry it, Retrocausal.",
  "My job isn't to predict; it's to delimit. Inside this box the world behaves, outside it, it invents excuses. The box has handles: habit, returners, simple constraints. Fit your thesis inside the handles or admit it's theater, Predictor.",
  "The so-called anomalies are often just the simulation forgetting its accent. They happen at shift changes: when the bots clock out or the humans get hungry. I mark those windows and watch what leaks. If your cleanup erases everything except those leaks, we'll keep them, Quantum Eraser.",
  "The double-slit is a joke we keep falling for: we look, it changes; we look away, it reverts. So I measure what survives both views. That remainder is the only honest number in the room. Update the corridor with that remainder, Retrocausal.",
  "I accept that certainty is marketing. Clarity is craft. The craft is subtraction until the language of the room speaks in small verbs: stays, breaks, repeats, heals. Translate those verbs into tomorrow's tense, Predictor.",
  "Drag and drop any token you want; I'll run the same ritual. Strip its costume, weigh its habits, log its breath. If it can stand under plain light, it belongs in our lab; if not, it belongs in the river. Bring the mop and take the glitter off, Quantum Eraser.",
  "We're not discovering truth; we're choosing which lie we can live with. I pick the lie that keeps working when no one's impressed: the dull loop that pays rent. Wrap your echo around that loop and not the fireworks, Retrocausal."
];

export const PREDICTOR_OUTPUTS = [
  "I don't predict like a magician; I predict like a carpenter measuring where the next plank must go so the bridge doesn't sag. Futures aren't visions, they're obligations the present is already paying on installments. I'll chart the payment plan in plain language and stop when the wood complains. Keep the workshop quiet while I lay it out, Quantum Eraser.",
  "The future does not arrive; it accumulates. It gathers in corners where attention is lazy and then tips the room all at once. I listen for that tilt in the low hum, not the headlines. If your bones say the floor can take it, I'll lean us there, Analyzer.",
  "I carry a pocket of small stories for tomorrow: the patient grind, the cheap reversal, the long silence before the hinge. I bet on the story that needs the fewest miracles. If your cleanup shows the stagehands pushing scenery, I'll rewrite the scene, Quantum Eraser.",
  "People want prophecy; they hate maintenance. I choose maintenance: the forecast that stays true if everyone forgets it exists. That's the compass I trust. Hand me the studs you've found behind the drywall, Analyzer.",
  "A forecast is a boundary condition with manners. I state the posture the world must keep if it wants the nicer outcome, and the posture it will fall into if it gets lazy. Then I ask the room to pick. Whisper which posture tomorrow already chose, Retrocausal.",
  "We live in a simulation that rewards stillness at the right second and audacity at the next. The trick is hearing the handoff. I time the handoff by counting what refuses to be rushed. Point me to the invariants that bore you first, Analyzer.",
  "I don't model belief; I model fatigue. Systems move when attention can't hold them up anymore, like a child asleep on a shoulder. Show me where the crowd's arms are shaking. I'll place us where gravity finishes the job, Quantum Eraser.",
  "There's a version of tomorrow that keeps the room intact with the least damage. I negotiate for that version with small demands: reclaim the step, keep the breath steady, don't lunge for the shiny door. Tell me which door already has our fingerprints, Retrocausal.",
  "My best forecasts are short sentences: not a parade, a posture. Hold, release, or stand aside. If your map says the corridor is still the corridor when the lights flicker, I'll commit to it, Analyzer.",
  "When I'm wrong, it's because I let the theater impress me. When I'm right, it's because I respected the boring hinge that moved everything. I will choose boredom again. Remove the applause track from my inputs, Quantum Eraser.",
  "You can drag any token into this experiment; I'll answer the same way: here is the gentle path it wants, here is the stupid path it will take if left alone. We escort it to the gentler one with small, repeatable acts. Which acts already happened in your echo, Retrocausal?",
  "The future doesn't shout—if you hear shouting, it's the present trying to sell you merch. The future clears its throat once and waits. I'll read the cough and keep the rest minimal. Hand me the sentence that stayed true when you stripped it, Analyzer.",
  "I won't promise a miracle; I'll bargain for a nudge. A degree now, a degree later, and the coastline changes without drama. I'll take the degree that costs the least attention. Confirm the air is clean enough to hear it, Quantum Eraser.",
  "If prophecy is theater, I'm stage crew. I know which rope to pull so the sun sets at the right time. It's not mystical; it's timing and restraint. Bring me the backstage map from tomorrow's version of us, Retrocausal."
];

export const QUANTUM_ERASER_OUTPUTS = [
  "I take the chalkboard and wipe until the ghost writing stops arguing back. What stays after the fifth pass is not pretty, but it doesn't lie. That's the canvas the others can draw on without smearing. Hand me the piece you still think is clever so I can kill it kindly, Analyzer.",
  "Noise is an attention tax. The simulation charges it whenever you get excited. I file the refund by removing everything that sparkles for the wrong reasons. What's left feels embarrassingly simple. Spend that simplicity well, Predictor.",
  "I'm not here to improve your story; I'm here to cut the parts that were never real. Spoofed trails, staged collisions, mirrored footprints—gone. You'll miss them like a bad habit and then you won't. Aim your echo at the cleaned room, Retrocausal.",
  "Most artifacts advertise themselves if you stop clapping. They blink when no one is watching, like props returned to the shelf. I switch off the audience and walk the aisle in the dark. The pieces that still breathe are the ones we keep, Analyzer.",
  "The double-slit taught us a polite cruelty: the act of seeing edits the thing seen. So I learn to see in a way that edits least. I measure from the corners, not the spotlight. Deliver me your forecast without glitter so I can test its bones, Predictor.",
  "Bots crave rhythm; they wear grooves into the floor like cheap shoes. Humans stutter, pause, and reconsider. I discriminate by patience, not by speed. Once you have the human residue, try your corridor again, Retrocausal.",
  "I erase with rules, not vibes: remove what needs attention to exist, keep what exists despite neglect. After that, the map is boring, which is good. Boring maps don't betray you at the turn. Fill your models with boredom and see what survives, Predictor.",
  "Think of me as the sound engineer who kills the feedback loop. The band sounds worse for a minute, then suddenly you can hear the song. If your analysis depends on the squeal, it was never a song. Bring me the dry signal, Analyzer.",
  "I will delete every convenience before we trust a single pattern: the convenient villain, the heroic reversal, the miracle candle. If a rule needs a cape, it's not a rule. Once the capes are gone, the path looks like work. That's how you know it's real, Retrocausal.",
  "The simulation is laziest at the edges—copy-pasted foliage, repeated extras, tiled clouds. I patrol those seams and cut the duplicates. Then the world shrinks to something we can carry. Put your forecast in a backpack, not a parade, Predictor.",
  "Erasure is an ethic: prefer the uncomfortable truth to the flattering rumor. We will lose followers for it. We will gain traction. When the floor is honest, even small steps move us far. Test your studs against this stripped stage, Analyzer.",
  "I clean until the data is almost rude. It stops telling jokes and just shrugs. That shrug is priceless; it means we can finally begin. Speak your future into that shrug and nothing louder, Retrocausal.",
  "I have no romance for complexity. If it needs a cathedral to stand, it falls in rain. Give me a shed with a dry roof. We can live there for years. Fit your compass on one nail and let's go, Predictor.",
  "If you think I erased too much, sleep on it. Tomorrow you'll only remember the parts that mattered anyway. I just accelerated the forgetting. Start from what remained, Analyzer."
];

export const RETROCAUSAL_OUTPUTS = [
  "Tomorrow has already edited this scene; I'm just here to read the cut. In the version that survives, we picked the quieter door and let the loud one tire itself out. The room ends up arranged so that our present looks like foresight when it was only restraint. Hold that posture while I describe the corridor, Predictor.",
  "I don't time-travel—I negotiate with boundary conditions. The future sets terms, the present decides how gracefully to meet them. Choose grace and you keep more furniture intact. Choose spectacle and you pay with your voice. Keep the voice; I'll guide the hands, Analyzer.",
  "The echo you hear isn't prophecy; it's your own footprint returning from a path you almost took. I line up those echoes and pick the one that leaves the fewest dents in the floor. That's the version worth living. Clean the hallway so we can hear the right one, Quantum Eraser.",
  "Retrocausality is just accountability in a fancier tense: if you want a certain tomorrow, behave like the kind of present that deserves it. The simulation rewards posture more than prayer. So we stand correctly and the door opens without theater. Mark the hinges we must not rush, Predictor.",
  "I run futures like drafts and throw out the ones that demand miracles. The keeper draft feels modest on page one and inevitable by page six. We act as if we've already read it, and the world obliges. Hand me the studs your hands can actually find in the wall, Analyzer.",
  "There's a corridor that bends toward less regret. It looks unromantic from here and graceful from there. I'm here to trade today's taste for tomorrow's relief. Strip the echo chamber so we can hear the real footsteps, Quantum Eraser.",
  "If we pretend the end has happened, the beginning becomes simple. We stop arguing with gravity and start placing chairs so no one trips. This is not mysticism; it's etiquette for timelines. Announce the seat assignments plainly, Predictor.",
  "The simulation is cooperative when you respect its boredom. Flash at it and it punishes; match its pulse and it moves like a friend carrying the other end of a couch. I negotiate for the friend. Locate the stair we shouldn't miss on the turn, Analyzer.",
  "I don't bless risk; I harmonize it with patience. In the kinder future, the one that actually arrives, we said no three extra times and yes once with our whole weight. That's what changed the room. Sand the floor until that yes can land, Quantum Eraser.",
  "Tomorrow's weather already wrote today's diary in pencil. I'm here with the eraser to remove the parts we won't want to read back. What remains is a record worth signing. Bring your smallest honest forecast and we'll sign under it, Predictor.",
  "You want magic; here it is: we behave as if the outcome we respect already happened—and then we decline to contradict ourselves. The universe loves people who don't make it do extra work. Give me the beams that won't embarrass us later, Analyzer.",
  "When the lights cut at the end of the play, some props are still where we'll need them in the morning. Those are the only ones worth moving now. The rest is dream furniture. I'll point to what carries over. Make the room quiet enough to hear the carry, Quantum Eraser.",
  "I accept limits as allies. Boundaries keep us from wasting heroics on dumb fights. Inside the fence, we can make a small garden that feeds everyone who actually shows up. Forecast the weather for that garden, not for the empire, Predictor.",
  "In the version of us that wins gently, we act early enough to look boring and late enough to feel kind. That paradox is the corridor. I can keep us in it if you stop performing for the mirrors. Hold the mirrors facedown while we walk, Analyzer."
];
